rooibos/access/urls.py
from django.conf.urls.defaults import *
from views import *

urlpatterns = patterns('',
    url(r'^effective-permissions/(?P<app_label>[\w-]+)/(?P<model>[\w-]+)/(?P<id>\d+)/(?P<name>[\w-]+)/$', effective_permissions, name='access-effective-permissions'),
    url(r'^modify/(?P<app_label>[\w-]+)/(?P<model>[\w-]+)/(?P<id>\d+)/(?P<name>[\w-]+)/$', modify_permissions, name='access-modify-permissions'),
)

rooibos/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
from django.views.generic.simple import direct_to_template
from django.views.static import serve
from django.views.decorators.cache import cache_control
from django.http import HttpResponseServerError
from django.template import loader, RequestContext
from rooibos.ui.views import main
from rooibos.access.views import login, logout
from rooibos.legacy.views import legacy_viewer


admin.autodiscover()

apps = filter(lambda a: a.startswith('apps.'), settings.INSTALLED_APPS)
apps_showcases = list(s[5:].replace('.', '-') + '-showcase.html' for s in apps)

# Cache static files
serve = cache_control(max_age=365 * 24 * 3600)(serve)

def handler500_with_context(request):
    template = loader.get_template('500.html')
    return HttpResponseServerError(template.render(RequestContext(request)))

handler404 = getattr(settings, 'HANDLER404', handler404)
handler500 = getattr(settings, 'HANDLER500', handler500_with_context)


def raise_exception():
    raise Exception()


urls = [
    # main page needs SSL because of embedded login form, otherwise CSRF fails
    url(r'^$', main, {'HELP': 'frontpage', 'SSL': True}, name='main'),
    url(r'^about/', direct_to_template, {'template': 'about.html'}, name='about'),
    url(r'^showcases/', direct_to_template, {'HELP': 'showcases',
                                             'template': 'showcases.html',
                                             'extra_context': {'applications': apps_showcases}}, name='showcases'),
    url(r'^login/$', login, {'HELP': 'logging-in', 'SSL': True}, name='login'),
    url(r'^logout/$', logout, {'HELP': 'logging-out', 'next_page': settings.LOGOUT_URL}, name='logout'),
#    url(r'^admin/(.*)', admin.site.root, {'SSL': True}, name='admin'),
    (r'^admin/', include(admin.site.urls)),

    # Legacy URL for presentation viewer in earlier version
    url(r'^viewers/view/(?P<record>\d+)/.+/$', legacy_viewer),

    (r'^ui/', include('rooibos.ui.urls')),
    (r'^acl/', include('rooibos.access.urls')),
    (r'^explore/', include('rooibos.solr.urls')),
    (r'^media/', include('rooibos.storage.urls')),
    (r'^data/', include('rooibos.data.urls')),
    (r'^legacy/', include('rooibos.legacy.urls')),
    (r'^presentation/', include('rooibos.presentation.urls')),
    (r'^viewers/', include('rooibos.viewers.urls')),
    (r'^workers/', include('rooibos.workers.urls')),
    (r'^convert/', include('rooibos.converters.urls')),
    (r'^api/', include('rooibos.api.urls')),
    (r'^profile/', include('rooibos.userprofile.urls')),
    (r'^federated/', include('rooibos.federatedsearch.urls')),
#    (r'^nasa/', include('rooibos.federatedsearch.nasa.urls')),
    (r'^flickr/', include('rooibos.federatedsearch.flickr.urls')),
    (r'^artstor/', include('rooibos.federatedsearch.artstor.urls')),
    (r'^impersonate/', include('rooibos.contrib.impersonate.urls')),
    (r'^mediaviewer/', include('rooibos.mediaviewer.urls')),
    (r'^megazine/', include('rooibos.megazine.urls')),
    (r'^pdfviewer/', include('rooibos.pdfviewer.urls')),
    (r'^pptexport/', include('rooibos.pptexport.urls')),
    (r'^audiotextsync/', include('rooibos.audiotextsync.urls')),

    url(r'^favicon.ico$', serve, {'document_root': settings.STATIC_DIR, 'path': 'images/favicon.ico'}),
    url(r'^robots.txt$', serve, {'document_root': settings.STATIC_DIR, 'path': 'robots.txt'}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_DIR}, name='static'),

    url(r'^exception/$', raise_exception),
    ]

for app in apps:
    if not '.' in app[5:]:
        urls.append(url(r'^%s/' % app[5:], include('%s.urls' % app)))

urlpatterns = patterns('', *urls)

rooibos/access/models.py
from django.db import models
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User, Group
from rooibos.contrib.ipaddr import IP


class AccessControl(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index=True)
    content_object = generic.GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, null=True, blank=True)
    usergroup = models.ForeignKey(Group, null=True, blank=True)
    read = models.NullBooleanField()
    write = models.NullBooleanField()
    manage = models.NullBooleanField()
    restrictions_repr = models.TextField(blank=True, default='')


    class Meta:
        unique_together = ('content_type', 'object_id', 'user', 'usergroup')

    def save(self, **kwargs):
        if (self.user and self.usergroup):
            raise ValueError("Mutually exclusive fields set")
        super(AccessControl, self).save(kwargs)

    def __unicode__(self):
        def f(flag, char):
            if flag == True: return char
            elif flag == False: return char.upper()
            else: return '-'
        return '%s [%s%s%s] %s (%s)' % (self.user or self.usergroup or 'AnonymousUser',
                                 f(self.read, 'r'), f(self.write, 'w'), f(self.manage, 'm'),
                                 self.content_object, self.content_type)

    def restrictions_get(self):
        if self.restrictions_repr:
            return eval(self.restrictions_repr, {"__builtins__": None}, {})
        else:
            return None

    def restrictions_set(self, value):
        if value:
            self.restrictions_repr = repr(value)
        else:
            self.restrictions_repr = ''

    restrictions = property(restrictions_get, restrictions_set)


EVERYBODY_GROUP = 'E'
AUTHENTICATED_GROUP = 'A'
IP_BASED_GROUP = 'I'
ATTRIBUTE_BASED_GROUP = 'P'


def update_membership_by_attributes(user, info):
    for group in ExtendedGroup.objects.filter(type=ATTRIBUTE_BASED_GROUP):
        group.update_membership_by_attributes(user, info)
    return True


class ExtendedGroupManager(models.Manager):

    def get_extra_groups(self, user, assume_authenticated=False):
        # retrieve membership in special groups such as everyone and authenticated users
        # membership for those types of groups is not stored explicitly
        q = Q(type=EVERYBODY_GROUP)
        if assume_authenticated or user.is_authenticated():
            q = q | Q(type=AUTHENTICATED_GROUP)
        ip_group_memberships = getattr(user, '_cached_ip_group_memberships', [])
        if ip_group_memberships:
            q = q | Q(id__in=ip_group_memberships)
        return self.filter(q)


class ExtendedGroup(Group):
    TYPE_CHOICES = (
        ('A', 'Authenticated'),
        ('I', 'IP Address based'),
        ('P', 'Attribute based'),
        ('E', 'Everybody'),
    )

    type = models.CharField(max_length=1, choices=TYPE_CHOICES)

    objects = ExtendedGroupManager()

    # to be called upon a user login
    def update_membership_by_attributes(self, user, info=None):
        if self.type == ATTRIBUTE_BASED_GROUP:
            if info and self._check_attributes(info):
                self.user_set.add(user)
            else:
                self.user_set.remove(user)

    def _check_subnet(self, address):
        ip = IP(address)
        for subnet in self.subnet_set.values_list('subnet', flat=True):
            if ip in IP(subnet):
                return True
        return False

    def _check_attributes(self, attributes):
        for attribute in Attribute.objects.filter(group=self):
            values = attributes.get(attribute.attribute, [])
            for value in attribute.attributevalue_set.all().values_list('value', flat=True):
                if (hasattr(values, '__iter__') and value in values) or value == values:
                    break
            else:
                return False
        return True

    def _full_type(self):
        return filter(lambda (a,f): a==self.type, self.TYPE_CHOICES)[0][1]

    def __unicode__(self):
        return '%s (%s)' % (self.name, self._full_type())

class Subnet(models.Model):
    group = models.ForeignKey(ExtendedGroup, limit_choices_to={'type': 'I'})
    subnet = models.CharField(max_length=80)

    def __unicode__(self):
        return '%s: %s' % (self.group.name, self.subnet)


class Attribute(models.Model):
    group = models.ForeignKey(ExtendedGroup, limit_choices_to={'type': 'P'})
    attribute = models.CharField(max_length=255)

    def __unicode__(self):
        return '%s: %s' % (self.group.name, self.attribute)


class AttributeValue(models.Model):
    attribute = models.ForeignKey(Attribute)
    value = models.CharField(max_length=255)

rooibos/access/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, get_list_or_404, render_to_response
from django.template import RequestContext
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.views import login as dj_login, logout as dj_logout
from django.conf import settings
from django import forms
from django.core.urlresolvers import reverse
from django.contrib.auth import REDIRECT_FIELD_NAME
from models import AccessControl
from . import check_access, get_effective_permissions_and_restrictions, get_accesscontrols_for_object
from rooibos.statistics.models import Activity
import re


def login(request, login_url=None, redirect_field_name=REDIRECT_FIELD_NAME,
          *args, **kwargs):
    if request.user.is_authenticated():
        # Similar redirect_to processing as in django.contrib.auth.views.login
        redirect_to = request.REQUEST.get(redirect_field_name, '')
        # Light security check -- make sure redirect_to isn't garbage.
        if not redirect_to or ' ' in redirect_to:
            redirect_to = settings.LOGIN_REDIRECT_URL
        # Heavier security check -- redirects to http://example.com should
        # not be allowed, but things like /view/?param=http://example.com
        # should be allowed. This regex checks if there is a '//' *before* a
        # question mark.
        elif '//' in redirect_to and re.match(r'[^\?]*//', redirect_to):
            redirect_to = settings.LOGIN_REDIRECT_URL
        return HttpResponseRedirect(redirect_to)
    try:
        response = dj_login(request, *args, **kwargs)
    except ValueError:
        # Certain values in the database password field can cause a ValueError
        # in that case, return a redirect back to the login page
        return HttpResponseRedirect((login_url or reverse('login')) + '?' + request.GET.urlencode())
    if type(response) == HttpResponseRedirect:
        # Successful login, add user to IP based groups
        Activity.objects.create(event='login',
                                request=request,
                                content_object=request.user)

    return response


def logout(request, *args, **kwargs):
    if request.session.get('unsafe_logout'):
        return render_to_response('unsafe_logout.html',
                                  {},
                                  context_instance=RequestContext(request))
    else:
        kwargs['next_page'] = request.GET.get('next', kwargs.get('next_page', settings.LOGOUT_URL))
        return dj_logout(request, *args, **kwargs)


def effective_permissions(request, app_label, model, id, name):
    try:
        contenttype = ContentType.objects.get(app_label=app_label, model=model)
        object = contenttype.get_object_for_this_type(id=id)
    except ObjectDoesNotExist:
        raise Http404
    check_access(request.user, object, manage=True, fail_if_denied=True)

    username = request.GET.get('user')
    if username:
        acluser = User.objects.filter(username=username)
        if acluser:
            acluser = acluser[0]
            acl = get_effective_permissions_and_restrictions(acluser, object, assume_authenticated=True)
        else:
            request.user.message_set.create(message="No user with username '%s' exists." % username)
            acl = None
    else:
        acluser = None
        acl = None

    return render_to_response('access_effective_permissions.html',
                              {'object': object,
                               'contenttype': contenttype,
                               'acluser': acluser,
                               'acl': acl,
                               'qsuser': username,
                               },
                              context_instance=RequestContext(request))


def modify_permissions(request, app_label, model, id, name):

    try:
        contenttype = ContentType.objects.get(app_label=app_label, model=model)
        object = contenttype.get_object_for_this_type(id=id)
    except ObjectDoesNotExist:
        raise Http404
    check_access(request.user, object, manage=True, fail_if_denied=True)

    permissions = get_accesscontrols_for_object(object)

    def tri_state(value):
        return None if value == 'None' else value == 'True'

    class ACForm(forms.Form):
        read = forms.TypedChoiceField(choices=((None, 'Not set'), (True, 'Allowed'), (False, 'Denied')), coerce=tri_state)
        write = forms.TypedChoiceField(choices=((None, 'Not set'), (True, 'Allowed'), (False, 'Denied')), coerce=tri_state)
        manage = forms.TypedChoiceField(choices=((None, 'Not set'), (True, 'Allowed'), (False, 'Denied')), coerce=tri_state)
        restrictions = forms.CharField(widget=forms.Textarea(attrs={'style': 'max-height: 100px;'}), required=False)

        def clean_restrictions(self):
            r = unicode(self.cleaned_data['restrictions'])
            if not r:
                return None
            try:
                return dict(map(unicode.strip, kv.split('=', 1)) for kv in filter(None, map(unicode.strip, r.splitlines())))
            except Exception, e:
                raise forms.ValidationError('Please enter one key=value per line')

    if request.method == "POST":
        acobjects = AccessControl.objects.filter(id__in=request.POST.getlist('ac'),
                                             content_type=contenttype,
                                             object_id=id)
        if request.POST.get('delete'):
            acobjects.delete()
            return HttpResponseRedirect(request.get_full_path())
        else:
            ac_form = ACForm(request.POST)
            if ac_form.is_valid():

                def set_ac(ac):
                    ac.read = ac_form.cleaned_data['read']
                    ac.write = ac_form.cleaned_data['write']
                    ac.manage = ac_form.cleaned_data['manage']
                    ac.restrictions = ac_form.cleaned_data['restrictions']
                    ac.save()

                map(set_ac, acobjects)

                username = request.POST.get('adduser')
                if username:
                    try:
                        user = User.objects.get(username=username)
                        ac = AccessControl.objects.filter(user=user, content_type=contenttype, object_id=id)
                        if ac:
                            set_ac(ac[0])
                        else:
                            set_ac(AccessControl(user=user, content_type=contenttype, object_id=id))
                    except User.DoesNotExist:
                        request.user.message_set.create(message="No user with username '%s' exists." % username)

                groupname = request.POST.get('addgroup')
                if groupname:
                    try:
                        group = Group.objects.get(name=groupname)
                        ac = AccessControl.objects.filter(usergroup=group, content_type=contenttype, object_id=id)
                        if ac:
                            set_ac(ac[0])
                        else:
                            set_ac(AccessControl(usergroup=group, content_type=contenttype, object_id=id))
                    except Group.DoesNotExist:
                        request.user.message_set.create(message="No group with name '%s' exists." % groupname)

                return HttpResponseRedirect(request.get_full_path())
    else:
        ac_form = ACForm()

    return render_to_response('access_modify_permissions.html',
                              {'object': object,
                               'contenttype': contenttype,
                               'permissions': permissions,
                               'ac_form': ac_form,
                               },
                              context_instance=RequestContext(request))

rooibos/access/templates/access_effective_permissions.html
{% extends "master.html" %}
{% load help %}
{% load access_control %}
{% load ui %}

{% block sidebar %}

{% var as related_pages %}
{"pages": [
{% include "ui_related_pages_for_object.html" %}
]}
{% endvar %}
{{ block.super }}

<div class="facet active-facet">
  <div class="facet-header">Permissions (<a href="{% permissions_modify_url object %}">Modify</a>)</div>
  <div class="facet-body">
      {% permissions_display object %}
  </div>
</div>

{% endblock %}


{% block content %}

<h1>{% if object.get_absolute_url %}<a href="{{ object.get_absolute_url }}">{{ object.title }}</a>{% else %}{{ object.title }}{% endif %}</h1>

<form style="margin-bottom: 20px;" method="GET" action="{% url access-effective-permissions contenttype.app_label, contenttype.model, object.id, object.name %}">
<label for="access_effective_permissions_user">Calculate effective permissions on this object for user:</label>
<input type="text" name="user" id="access_effective_permissions_user" class="autocomplete-user" value="{{ qsuser }}" />
<input type="submit" value="Calculate" />
</form>

{% if acluser %}

<h2>Effective permissions for {{ acluser }}{% if acluser.last_name %} ({{ acluser.last_name }}{% if acluser.first_name %}, {{ acluser.first_name }}{% endif %}){% endif %}</h2>

<ul>
    <li>Read: {{ acl.0|yesno:"Allowed,Denied,Unspecified" }}</li>
    <li>Write: {{ acl.1|yesno:"Allowed,Denied,Unspecified" }}</li>
    <li>Manage: {{ acl.2|yesno:"Allowed,Denied,Unspecified" }}</li>
    <li>Restrictions: {% if acl.3 %}
      <ul>{% for k, v in acl.3.iteritems %}
        <li>{{ k }}: {{ v }}</li>
        {% endfor %}
      </ul>
      {% else %}
      None
      {% endif %}
    </li>
</ul>

<h3>Group membership</h3>

{{ acluser }} is currently a member of the following groups:
<ul>
{% for group in acluser.groups.all %}
<li>{{ group.name }}</li>
{% empty %}
<li>No explicit group memberships found.</li>
{% endfor %}
<li>Authenticated Users (always assumed)</li>
</ul>

<h3>Administrator status</h3>

{{ acluser }} is {{ acluser.is_superuser|yesno:",not" }} an administrator.

{% endif %}



{% endblock %}

rooibos/access/templates/access_effective_permissions_form.html
<form method="GET" action="{% url access-effective-permissions contenttype.app_label, contenttype.model, object.id, object.name %}">
<label for="access_effective_permissions_user">Calculate effective permissions on this object for user:</label>
<input type="text" name="user" id="access_effective_permissions_user" class="autocomplete-user" /><br />
<input type="submit" value="Calculate" />
</form>

rooibos/access/templates/access_modify_permissions.html
{% extends "master.html" %}
{% load help %}
{% load access_control %}
{% load ui %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">

    $("input[name=ac]").click(function() {
        if (this.checked) {
            var read = $(this).next('span');
            var write = read.next('span');
            var manage = write.next('span');
            var restrictions = manage.next('span');
            $("#id_read").attr('selectedIndex', read.hasClass('a') * 1  + read.hasClass('d') * 2)
            $("#id_write").attr('selectedIndex', write.hasClass('a') * 1  + write.hasClass('d') * 2)
            $("#id_manage").attr('selectedIndex', manage.hasClass('a') * 1  + manage.hasClass('d') * 2)
            $("#id_restrictions").val(restrictions.data('title') || "");
        }
    });

</script>
{% endblock %}

{% block sidebar %}
{% var as related_pages %}
{"pages": [
{% include "ui_related_pages_for_object.html" %}
]}
{% endvar %}
{{ block.super }}
{% endblock %}

{% block content %}

<h1>Modify permissions for {{ object.title }}</h1>

<form method="POST" action=".">{% csrf_token %}
{% with "true" as ac_selectable %}
{% include "access_permissions_display.html" %}
{% endwith %}
<br />

Set selected and new access controls to:
<table>
{{ ac_form }}
<tr>
    <td>Add user:</td>
    <td><input type="text" class="autocomplete-user" name="adduser" /></td>
</tr>
<tr>
    <td>Add group:</td>
    <td><input type="text" class="autocomplete-group" name="addgroup" /></td>
</tr>
</table>


<input type="submit" value="Submit changes" />

<br /><br />

<input type="submit" value="Remove selected access controls" name="delete" />


</form>

{% endblock %}

rooibos/access/templates/access_permissions_display.html
<div class="permission-list">
{% for ac in permissions %}
{% if ac_selectable %}
<input type="checkbox" name="ac" value="{{ ac.id }}" />
{% endif %}
<span class="{{ ac.read|yesno:"a,d,u" }}">R</span>
<span class="{{ ac.write|yesno:"a,d,u" }}">W</span>
<span class="{{ ac.manage|yesno:"a,d,u" }}">M</span>
<span class="{{ ac.restrictions|yesno:"a,u,u" }}"{% if ac.restrictions %} title="{% for k,v in ac.restrictions.iteritems %}{{ k }}={{ v }}
{% endfor %}"{% endif %}>&reg;</span>
{% if ac.user %}<img src="{% url static 'images/user.png' %}" alt="User" class="user-icon" />
<a href="{% url access-effective-permissions contenttype.app_label, contenttype.model, object.id, object.name %}?user={{ ac.user.username|urlencode }}">{{ ac.user.username }}</a>
{% else %}{% if ac.usergroup %}<img src="{% url static 'images/group.png' %}" alt="Group" class="user-icon" /> {{ ac.usergroup.name }}{% else %}Anonymous Users{% endif %}{% endif %}<br />
{% empty %}
{{ emptymessage|default:"No permissions set." }}
{% endfor %}
</div>

rooibos/access/templates/unsafe_logout.html
{% extends "master.html" %}

{% block content %}
<h1>Logout unavailable</h1>

You logged into MDID in a way that does not allow you to be logged out reliably.  Please close your browser to log out.
{% endblock %}